In [32]:
import numpy as np
import operator

In [33]:
A = [[1,3,0],
     [8,2,4],
     [7,6,5]]
B = [[1,2,3],
     [8,0,4],
     [7,6,5]]
     
k = 0
BeginState = np.zeros((3,3))
EndState = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        BeginState[i][j] = A[i][j]
        EndState[i][j] = B[i][j]
        
print(BeginState)
print(EndState)

[[1. 3. 0.]
 [8. 2. 4.]
 [7. 6. 5.]]
[[1. 2. 3.]
 [8. 0. 4.]
 [7. 6. 5.]]


In [34]:
openlist=[]#open表

class State:
    def __init__(self,m):
        self.node=m #节点代表的状态
        self.f=0  #f(n)=g(n)+h(n)
        self.g=0 #g(n)
        self.h=0 #h(n)
        self.father=None #节点的父亲节点

init = State(BeginState) #初始状态
goal=State(EndState) #目标状态

def h(state):
    Mval = 0
    for i in range(3):
        for j in range(3):
            Mval += abs(state.node[i][j] - goal.node[i][j])
    return Mval

def list_sort(l):
    cmp = operater.attrgetter('f')
    l.sort(key = cmp)

def find_zero(node):
    for i in range(3):
            for j in range(3):
                if node[i][j] == 0:
                    x_0, y_0 = i, j
            if node[i][j] == 0:
                    x_0, y_0 = i, j
    return x_0,y_0

def A_star(state):
    global openlist
    openlist.append(state)
    fatherlist = [state.node]

    while (openlist):
        first = openlist[0]
        if (first.node == goal.node).all():
            return first
        openlist.remove(first)
        x_0,y_0 = find_zero(first.node)
        
        for i in range(3):
            for j in range(3):
                c = first.node.copy()
                if (i - x_0)**2 + (j - y_0)**2 == 1:
                    c[x_0][y_0] = c[i][j]
                    c[i][j] = 0
                    next_node = State(c)
                    
                    for k in range(len(fatherlist)):
                        if (next_node.node == fatherlist[k]).all():
                            if next_node.f < fatherlist[k].f:
                                fatherlist[k] = next_node.node
                            break
                    
                    if k == len(fatherlist):
                        next_node.father = first
                        next_node.g = first.g + 1
                        next_node.h = h(next_node)
                        next_node.f = next_node.g + next_node.h
                        openlist.append(next_node)
                        list_sort(openlist)
                        fatherlist.append(next_node.node)
    return fatherlist

final = A_star(init)
for i in final:
    print(i)


                        




[[1. 3. 0.]
 [8. 2. 4.]
 [7. 6. 5.]]


In [35]:
import numpy as np
import operator
A = [[1,3,0],
     [8,2,4],
     [7,6,5]]
B = [[1,2,3],
     [8,0,4],
     [7,6,5]]
     
k = 0
M = np.zeros((3,3))
N = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        M[i][j] = A[i][j]
        N[i][j] = B[i][j]

openlist=[]#open表

class State:
    def __init__(self,m):
        self.node=m#节点代表的状态
        self.f=0#f(n)=g(n)+h(n)
        self.g=0#g(n)
        self.h=0#h(n)
        self.father=None#节点的父亲节点

init = State(M)#初始状态
goal=State(N)#目标状态

#启发函数（曼哈顿距离）
def h(node):
    Mval = 0
    for i in range(3):
        for j in range(3):
            Mval += abs(node[i][j] - goal.node[i][j])
    return Mval

#对节点列表按照估价函数的值的规则排序
def list_sort(l):
    cmp=operator.attrgetter('f')
    l.sort(key=cmp)

#A*算法    
def A_star(s):
    global openlist#全局变量可以让open表进行时时更新
    openlist=[s]
    fatherlist=[s]
    while(openlist):
        get=openlist[0] #取出open表的首节点  
        if (get.node==goal.node).all():#判断是否与目标节点一致
            return get
        openlist.remove(get)#将get移出open表
        #判断此时状态的空格位置
        for a in range(len(get.node)):
            for b in range(len(get.node[a])):
                if get.node[a][b] == 0:
                    break
            if get.node[a][b] == 0:
                break
        #开始移动
        for i in range(len(get.node)):
            for j in range(len(get.node[i])):
                c=get.node.copy()
                if (i-a)**2 + (j-b)**2 == 1:
                    c[a][b] = c[i][j]
                    c[i][j] = 0
                    new = State(c)
                    K = 0
                    for k in range(len(openlist)):
                        if (new.node == openlist[k].node).all():
                            if new.f < openlist[k].f:
                                openlist.pop(k) 
                                openlist.append(new)  
                            break
                        else:
                            K = K+1
                    if K == len(openlist):     
                        new.father = get#此时取出的get节点成为新节点的父亲节点
                        new.g = get.g+1#新节点与父亲节点的距离
                        new.h = h(new.node)#新节点的启发函数值
                        new.f = new.g + new.h#新节点的估价函数值
                        openlist.append(new)
                        list_sort(openlist)
    return openlist
                        


           
# 递归打印路径
def printpath(f):
    g = f
    length = 0
    while (g != None):
        length += 1
        g = g.father

    if f is None:
        return 
    printpath(f.father)
    print("step " + str(length))
    for i in range(3):
        for j in range(3):
            print(int(f.node[i][j]),end = ' ')
        print()
    


final=A_star(init)
printpath(final)
           


step 1
1 3 0 
8 2 4 
7 6 5 
step 2
1 0 3 
8 2 4 
7 6 5 
step 3
1 2 3 
8 0 4 
7 6 5 
