In [1]:
import numpy as np

In [8]:
A = [list(map(int,input().split())) for _ in range(3)]
B = [list(map(int,input().split())) for _ in range(3)]
k = 0
BeginState = np.zeros((3,3))
EndState = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        BeginState[i][j] = A[i][j]
        EndState[i][j] = B[i][j]
        
print(BeginState)
print(EndState)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
openlist=[]#open表

class State:
    def __init__(self,m):
        self.node=m#节点代表的状态
        self.f=0#f(n)=g(n)+h(n)
        self.g=0#g(n)
        self.h=0#h(n)
        self.father=None#节点的父亲节点

init = State()#初始状态
goal=State(N)#目标状态
